import type { Event, Review, User } from './types';

export const events: Event[] = [
  {
    id: '1',
    name: 'Annual Tech Conference',
    date: '2024-10-26T09:00:00',
    location: 'Metropolis Convention Center',
    category: 'Tech',
    description: 'The biggest tech conference of the year. Join us for talks from industry leaders.',
    longDescription: 'Dive deep into the latest trends in AI, blockchain, and cloud computing. Our annual conference brings together the brightest minds in technology for three days of networking, learning, and innovation. Featuring keynotes from CEOs of major tech companies, hands-on workshops, and a startup pitch competition.',
    imageUrl: 'https://picsum.photos/600/400',
    attendees: 450,
    capacity: 500,
  },
  {
    id: '2',
    name: 'Summer Music Fest',
    date: '2024-08-15T14:00:00',
    location: 'Sunset Park Amphitheater',
    category: 'Music',
    description: 'Three days of live music from your favorite bands and artists.',
    longDescription: 'Experience the ultimate summer music festival. With three stages, over 50 artists, and a variety of food trucks, it\'s the perfect way to spend a summer weekend. From rock to electronic, there\'s something for every music lover.',
    imageUrl: 'https://picsum.photos/600/401',
    attendees: 2800,
    capacity: 3000,
  },
  {
    id: '3',
    name: 'Modern Art Exhibition',
    date: '2024-09-05T11:00:00',
    location: 'The Grand Art Gallery',
    category: 'Art',
    description: 'Explore stunning works from contemporary artists around the globe.',
    longDescription: 'This exhibition showcases the vibrant and diverse world of modern art. Featuring paintings, sculptures, and installations from over 100 contemporary artists, "Visions of Now" is a must-see for art enthusiasts. Guided tours are available daily.',
    imageUrl: 'https://picsum.photos/600/402',
    attendees: 120,
    capacity: 200,
  },
  {
    id: '4',
    name: 'Gourmet Food Fair',
    date: '2024-09-21T12:00:00',
    location: 'City Market',
    category: 'Food',
    description: 'A paradise for foodies. Taste exquisite dishes from top chefs.',
    longDescription: 'Savor the flavors of the world at our annual Gourmet Food Fair. From street food classics to fine dining creations, dozens of vendors will be serving up their best dishes. Join us for cooking demonstrations, tasting sessions, and more.',
    imageUrl: 'https://picsum.photos/600/403',
    attendees: 850,
    capacity: 1000,
  },
  {
    id: '5',
    name: 'Community Cleanup Day',
    date: '2024-11-02T09:30:00',
    location: 'Greenwood Park',
    category: 'Community',
    description: 'Join us to help clean and beautify our local park.',
    longDescription: 'Let\'s make a difference together! Our Community Cleanup Day is a great opportunity to give back, meet your neighbors, and enjoy the outdoors. We\'ll provide all the necessary supplies. All ages are welcome.',
    imageUrl: 'https://picsum.photos/600/404',
    attendees: 75,
    capacity: 150,
  },
    {
    id: '6',
    name: 'Indie Film Festival',
    date: '2024-11-12T18:00:00',
    location: 'The Onyx Theater',
    category: 'Art',
    description: 'Discover the next generation of filmmakers at our annual indie fest.',
    longDescription: 'Celebrate independent cinema with a curated selection of feature films, shorts, and documentaries from talented filmmakers worldwide. The festival includes Q&A sessions with directors, panel discussions, and networking events.',
    imageUrl: 'https://picsum.photos/600/405',
    attendees: 180,
    capacity: 250,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    author: 'Jane Doe',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    rating: 5,
    comment: 'This was an amazing conference! So many great speakers and I learned a ton.',
  },
  {
    id: '2',
    author: 'John Smith',
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
    rating: 4,
    comment: 'Well organized and the topics were very relevant. The networking opportunities were fantastic.',
  },
  {
    id: '3',
    author: 'Alice Johnson',
    avatarUrl: 'https://i.pravatar.cc/150?img=3',
    rating: 3,
    comment: 'Some sessions were great, but others were a bit basic. The venue was too crowded.',
  },
  {
    id: '4',
    author: 'Mike Brown',
    avatarUrl: 'https://i.pravatar.cc/150?img=4',
    rating: 5,
    comment: 'Incredible event! The hands-on workshops were the best part. I\'ll definitely be back next year.',
  },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Carlos Alvarez',
    email: 'carlos@example.com',
    joinedDate: '2023-01-15',
    avatarUrl: '',
  },
  {
    id: '2',
    name: 'Beatrice Miller',
    email: 'beatrice@example.com',
    joinedDate: '2023-02-20',
    avatarUrl: '',
  },
  {
    id: '3',
    name: 'David Chen',
    email: 'david@example.com',
    joinedDate: '2023-03-10',
    avatarUrl: '',
  },
  {
    id: '4',
    name: 'Emily White',
    email: 'emily@example.com',
    joinedDate: '2023-04-05',
    avatarUrl: '',
  },
];
